API complete setup
tonnytech/hello-rails-back-end pull request #1
Opened 2023-10-25 06:54 UTC by tonnytech

Did the following in this branch:
- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

2023-10-25 07:59 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @tonnytech, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct . :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [ ] Check comment on your frontend PR

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 09:52 UTC, joel-kalema reviewed
Hi @tonnytech 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

![pirates-of-the-caribbean-johnny-depp](https://user-images.githubusercontent.com/57408419/242635897-074a8afb-6646-4281-8ff9-8390f857a9c5.gif)


- [ ] You have submitted a project that has linters that do not pass, make sure you solve them and then ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-25 10:50 UTC, Gambit142 requested changes
Hi @tonnytech 👋, 

Great work on making the changes requested by a previous reviewer 👏 

### Highlights
- Setup linters correctly ✔️ 
- Setup routes properly ✔️ 
- Setup Controllers and migrations correctly ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 10:50 UTC, Gambit142 commented on app/controllers/greetings_controller.rb
> +
- [ ] Great work attempting to resolve the **_CORS policy_** issue. However, the issue still persists. 

![image](https://github.com/tonnytech/hello-rails-back-end/assets/77106962/abfc371b-ce52-4c8c-8e84-1e0a169e9788)

---
 To solve the issue, you can install the `rack-cors` gem and then read through their [documentation](https://github.com/cyu/rack-cors) to resolve the **_CORS policy_** issue 👍 😎

2023-10-28 11:46 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @tonnytech**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- The API endpoint for returning a random greeting was created. ✔️ 
- The database table for storing different greetings was created. ✔️ 
- Correctly fix the CORS issue 👏🏻 💪🏻 

![image](https://github.com/AJ193/hello-react-front-end/assets/79058364/af1dae83-fd70-4237-8c13-85008260a232)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-09-05 05:59 UTC, merged